### ISSUE TITLE
Gateway Ingress for admin API 

### ISSUE THREAD

**Issue by erwan-b** [conduktor/conduktor-public-charts#105]
### Conduktor Gateway helm chart

If wanted to be able to expose the admin port with an ingress would be great.
The Ingress resource allow multiple feature give by the Ingress Controllers installed (self-managed or manage by a cloud provider)

Default `helm create` generate template give this values for the ingress, to me this could be enough.
```
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```
