### ISSUE TITLE
Helm should be able to parse non-string variables

### ISSUE THREAD

**Issue by chuck-alt-delete** [conduktor/conduktor-public-charts#119]
Here are two environment variables that should be accepted as int and bool respectively.

```
GATEWAY_ADVERTISED_SNI_PORT: "9092"
GATEWAY_FEATURE_FLAGS_INTERNAL_LOAD_BALANCING: "false"
```

There may be others

**Comment by qboileau** [comment]
We can't accept them as bool or int as they are to be passed using a ConfigMap that accept only string in current implementation. 
Even if they are defined as string in the values, they are passed as environment variables without quotes inside the container. 

You can also pass them directly to the deployment `env` using `gateway.extraSecretEnvVars` value.
Even if its name suggests it's only for secrets, you can actually pass env in standard kubernetes format like 
```yaml
gateway: 
    extraSecretEnvVars:
    - name: GATEWAY_ADVERTISED_SNI_PORT
      value: "9094"
    - name: GATEWAY_FEATURE_FLAGS_INTERNAL_LOAD_BALANCING
      value: "false"
``` 
They still need to be string in the definition but like for the current env that use ConfigMap they are mounted to the container without quotes.
