### ISSUE TITLE
Environment Variables with Dashes

### ISSUE THREAD

**Issue by gavinclarkeuk** [conduktor/conduktor-public-charts#129]
Several of the environment variables defined by the console chart contain dashes. Additional configurations for common functionality (e.g. SSO) also require dashes in the env var names. Kubernetes expects env var names to be C_IDENTIFIERS ([docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#envvar-v1-core)) where the only allowed special character is an underscore.

Whilst the Kubernetes schema does not explicitly block creation of env vars with dashes, many k8s implementations simply ignore these values, and they do not get reflected in the Pods environment.

This means that sevral configuraiton options defined int he chart aren't actually available to the Pod (e.g. `CDK_MONITORING_CLUSTERS-REFRESH-INTERVAL`). Furthermore there is no secure way to provide SSO settings via secrets with the current chart (e.g. `CDK_SSO_OAUTH2_0_CLIENT-SECRET`).

Whilst I appreciate this is more of a conduktor issue than a chart issue - conduktor should ideally use underscores instead of dashes for all env vars. If that isn't possible then this chart should provide a way to set the `platform-config.yaml` via a secret, instead of via a config map.

**Comment by qboileau** [comment]
Hi @gavinclarkeuk, thank you for your report. 

This is indeed a known issue with Conduktor Console configuration environment variable support, we currently can't change it without making big breaking changes in the configuration structure. 

But there is a workaround for that as Console support multiple syntax for all environment variables. You can indeed remove the dashes `-` in env var name. 
For example, `CDK_SSO_OAUTH2_0_CLIENT-SECRET` and `CDK_MONITORING_CLUSTERS-REFRESH-INTERVAL` can also be provided using `CDK_SSO_OAUTH2_0_CLIENTSECRET` and `CDK_MONITORING_CLUSTERSREFRESHINTERVAL`.

But there are some limitations and caution to have in mind when mixing env var with YAML configuration. 
Everything should be documented [here](https://docs.conduktor.io/platform/get-started/configuration/env-variables/#environment-variable-conversion) 

Another workaround is to leverage the support of [shell expansion in yamYAMLl configuration](https://docs.conduktor.io/platform/get-started/configuration/env-variables/#support-of-shell-expansion-in-the-yaml-configuration-file) to define you own env var name and simply add them using `platform.extraEnvVars` or `platform.extraEnvVarsCM` or `platform.extraEnvVarsSecret` in the chart values. 

Like this : 
**values.yaml**
```yaml
config:
  admin:
    email: "admin@my-org.com"
    password: "${ADMIN_PASSWORD}"

  database:
    host: "some.host"
    port: 5432
    name: "postgres"
    username: "${DB_LOGIN}"
    password: "${DB_PASSWORD}"
  sso:
    oauth2:
      - name: "sso"
        client-id: "${SSO_CLIENT_ID}"
        client-secret: "${SSO_CLIENT_SECRET}"
        openid:
          issuer: https://auth.host/
          
 platform: 
    extraEnvVarsSecret: "conduktor-secret"
``` 

With existing secrets

**conduktor-secrets.yaml**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: "conduktor-secret"
type: Opaque
data: 
   ADMIN_PASSWORD: ...
   DB_LOGIN: ...
   DB_PASSWORD: ...
   SSO_CLIENT_ID: ...
   SSO_CLIENT_SECRET: ...
``` 

Hope this help !
