### ISSUE TITLE
Console admin user password "you can only set it at install" -- it needs to be able to be overridden in the chart

### ISSUE THREAD

**Issue by mcpheesvoz** [conduktor/conduktor-public-charts#138]
From the Helm chart values file:

```
  admin:
    ## @param config.admin.email Your Conduktor Console Admin email, you can only set it at install! You will need to change it in the Conduktor Console UI after the installation
    email: ""
    ## @param config.admin.password Your Conduktor Console Admin password, you can only set it at install! You will need to change it in the Conduktor Console UI after the installation
    password: ""
```

You can refer to the internal support ticket https://support.conduktor.io/hc/en-gb/requests/1813 to see what issues this is causing.

In brief:

- Conduktor 1.29.0 now refuses to boot if admin password doesn't meet some arbitrary set of standards regarding password content.
- We use SSO / OAUTH logins
- Originally I set the admin email to be my email, I login via SSO
- I can't change my "internal" password via the Console because I login via SSO
- I can't change the admin user email via the Console (or how?)
- I can't change either the admin user email or its password via the Helm chart.
- I'm stuck, cannot upgrade to 1.29.0

I assume that I will be able to find a workaround of some sort, e.g. direct manipulation of the database.

However, it is highly desirable, if not essential, to be able to override and change the admin user email and password via the Helm chart, given that: the software now demands this information match some arbitrary standards or it refuses to work; **and** it is possible to have previously put the software into a configuration state that prevents both the upgrade and the changing of the password via the recommendation in the values file.
