### ISSUE TITLE
Console - local admin/users

### ISSUE THREAD

**Issue by GoncaloPT** [conduktor/conduktor-public-charts#58]
# Description
Environment variables related to[ local users](https://docs.conduktor.io/platform/get-started/configuration/user-authentication/local-admin-and-users/) are ignored.

## Problem Detail
I've setup a conduktor instance on my kubernetes cluster. I use a secret to setup the environment variables. Inside of that secret I've added 3 users using the stated format: 

```yaml
CDK_AUTH_LOCAL-USERS_0_EMAIL: ++++++++
CDK_AUTH_LOCAL-USERS_0_PASSWORD: ++++++++
CDK_AUTH_LOCAL-USERS_1_EMAIL: ++++++++
CDK_AUTH_LOCAL-USERS_1_PASSWORD: ++++++++
CDK_AUTH_LOCAL-USERS_2_EMAIL: ++++++++
CDK_AUTH_LOCAL-USERS_2_PASSWORD: ++++++++
```

Everything works fine other than the described bellow.

## Expected behavior
I would expect those 3 users would be created, but on the settings > users page I can only see the admin user. 

## Side note 1
I also noticed that I have no button to "Add member", only "Add group". 
Might this be related?

## Side note 2
I'm not sure dashes ( - ) are valid for environment variable keys.
When I try to print the value on the running pod, I cannot get the actual value.

**Comment by qboileau** [comment]
Hi @GoncaloPT 

I've just tested in [1.21.0](https://www.conduktor.io/changelog/Console-1.21.0#add-local-users-from-the-ui) and the local user environment variables work as expected using a docker compose or Console helm chart [1.6.0](https://github.com/conduktor/conduktor-public-charts/releases/tag/console-1.6.0) with `extraEnvVars` . 

```yaml
# my-value.yaml
platform:
  extraEnvVars:
    - name: CDK_AUTH_LOCAL-USERS_0_EMAIL
      value: xxxxxx
    - name: CDK_AUTH_LOCAL-USERS_0_PASSWORD
      value: xxxxxx
    - name: CDK_AUTH_LOCAL-USERS_1_EMAIL
      value: xxxxxx
    - name: CDK_AUTH_LOCAL-USERS_1_PASSWORD
      value: xxxxxx
    - name: CDK_AUTH_LOCAL-USERS_2_EMAIL
      value: xxxxxx
    - name: CDK_AUTH_LOCAL-USERS_2_PASSWORD
      value: xxxxxx
```
or using `extraEnvVarsSecret` like 
```yaml
#secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: console-users
  namespace: nsp
type: Opaque
data:
  CDK_AUTH_LOCAL-USERS_0_EMAIL: xxxx
  CDK_AUTH_LOCAL-USERS_0_PASSWORD: xxxx
  CDK_AUTH_LOCAL-USERS_1_EMAIL: xxxx
  CDK_AUTH_LOCAL-USERS_1_PASSWORD: xxxx
  CDK_AUTH_LOCAL-USERS_2_EMAIL: xxxx
  CDK_AUTH_LOCAL-USERS_2_PASSWORD: xxxx
```
```yaml
# my-value.yaml
platform:
  extraEnvVarsSecret: "console-users"
```

You can also use [yaml config](https://docs.conduktor.io/platform/get-started/configuration/user-authentication/local-admin-and-users/) to give local users using `config.auth.local-users` 
```yaml
# my-value.yaml
config:
  auth:
    local-users:
      - email: xxxxxx
        password: xxxxxx
      - email: xxxxxx
        password: xxxxxx
      - email: xxxxxx
        password: xxxxxx
```

> Side note 1

Since 1.21.0 you can actually create local users using Console UI ! :wink: 
Check our [changelog](https://www.conduktor.io/changelog/Console-1.21.0#add-local-users-from-the-ui) 

> Side note 2

In theory yes dash are not valid in environment variable name, but so far we didn't have real issue with it, `kubectl describe` on pod or other tool show them correctly.  
Console also support environment variables without the `-` dash like `CDK_AUTH_LOCALUSERS_0_EMAIL`  this did not mix well with YAML config file as an override.

Hope this help !
