### ISSUE TITLE
Adding extra objects via helm values.

### ISSUE THREAD

**Issue by demoxCZ** [conduktor/conduktor-public-charts#92]
Hi friends,

I would like to request the addition of this feature to the Helm chart via values:
extraObjects: []

A project that uses this feature can be found here:
https://github.com/argoproj/argo-helm/blob/50984954684e14bd6c43d19313d9487f78dd7237/charts/argo-cd/values.yaml#L576

Its really useful in case of automation of deployment via github/gitlab pipelines. In my case Id like to use it with combination of
Sealed secrets project.

example:
```
extraObjects:
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: conduktor-keycloak
      namespace: "{{ .Release.Namespace }}"
    spec:
      encryptedData:
        keycloak.clientSecret: .......
      template:
        metadata:
          creationTimestamp: null
          name: conduktor-keycloak
          namespace: "{{ .Release.Namespace }}"
          labels:
            app.kubernetes.io/part-of: conduktor
```

Thank you
